### ISSUE TITLE
Cannot build Lambda file in a Yarn Workspace

### ISSUE THREAD

**Issue by arantespp** [ttoss/carlin#8]
### Description

Error when importing a method from a Yarn Workspace package, like

```
import method from '@package/lib';
```

**Comment by sibelius** [comment]
the problem was here 

![image](https://user-images.githubusercontent.com/2005841/155141349-b861a9b5-0c84-432d-a3ea-d1fe2da4a834.png)

you need to let rollup bundle and handle node_modules/@package
